# source: https://rust-lang.github.io/mdBook/format/configuration/index.html
[book]
title = "Story Gametypes and Maps"
authors = ["Shtoyan"]
description = "Map lists for KF1 objective based gametypes."
src = "src"
language = "en"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true
extra-watch-dirs = []

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
no-section-label = true
git-repository-url = "https://github.com/InsultingPros/KFStory"
edit-url-template = "https://github.com/InsultingPros/KFStory/issues/new/choose"
site-url = "/KFStory/"
input-404 = "404.md"
